// <auto-generated />
using System;
using ClassManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929122218_TaiKhoanTuTaoVaQuenMatKhau")]
    partial class TaiKhoanTuTaoVaQuenMatKhau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassManagement.Api.Entities.BuoiHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime?>("GoogleDongBoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaBuoiDayBu")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("Ngay");

                    b.HasIndex("HocSinhId", "Ngay", "GioBatDau")
                        .IsUnique();

                    b.ToTable("BuoiHoc", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.CaiDat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("BatThongBaoHomNay")
                        .HasColumnType("bit");

                    b.Property<string>("DinhDangNgay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly>("GioGuiThongBaoHomNay")
                        .HasColumnType("time");

                    b.Property<string>("KyTuTienTe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MauNoiDungChuyenKhoan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MuiGio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayCapNhatUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguongCanhBaoSoHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("NhacTruocBaoLauPhut")
                        .HasColumnType("int");

                    b.Property<bool>("TinhTienNghiKhongPhep")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTroMacDinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CaiDat", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.DiemDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuoiHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CoTinhTien")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LyDoNghi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhatUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiDiemDanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThoiDiemDiemDanhUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThoiLuongThucTePhut")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BuoiHocId")
                        .IsUnique();

                    b.HasIndex("NguoiDiemDanhId");

                    b.ToTable("DiemDanh", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.GiaoVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("SoLanSaiMatKhau");

                    b.Property<string>("ChuTaiKhoan")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleRefreshTokenMaHoa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GoogleTaiKhoan")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("ChoPhepKhoa");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("KhoaDenLuc");

                    b.Property<string>("NganHangBin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayThamGia")
                        .HasColumnType("date");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EmailChuanHoa");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TenDangNhapChuanHoa");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhauBam");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TenDangNhap");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[TenDangNhapChuanHoa] IS NOT NULL");

                    b.HasIndex("TrangThai");

                    b.HasIndex("VaiTro");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocPhi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaChotSo")
                        .HasColumnType("bit");

                    b.Property<decimal>("DonGiaApDung")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HanDongTien")
                        .HasColumnType("date");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayChotUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoBuoiDiHoc")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoiNghiCoPhep")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoiNghiKhongPhep")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienDaThu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("HanDongTien");

                    b.HasIndex("HocSinhId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("HocPhi", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocSinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CachTinhHocPhi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DonGiaTheoBuoi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("HocPhiTheoThang")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayCapNhatUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NgayDenHanDongTien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuHuynh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoBuoiMoiTuan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoaiPhuHuynh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("HoTen");

                    b.HasIndex("TrangThai");

                    b.ToTable("HocSinh", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.KhungGioHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Thu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HocSinhId", "Thu", "GioBatDau")
                        .IsUnique();

                    b.ToTable("KhungGioHoc", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.NhatKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DoiTuongId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DuLieuSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuLieuTruoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("NguoiThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiDiemUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThucHienId");

                    b.HasIndex("ThoiDiemUtc");

                    b.HasIndex("DoiTuong", "DoiTuongId");

                    b.ToTable("NhatKy", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.PhienDangNhap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HetHanUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThuHoiUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ThayTheBoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThietBi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TokenBam")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("TokenBam")
                        .IsUnique();

                    b.ToTable("PhienDangNhap", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.PhieuThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("HocPhiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayThu")
                        .HasColumnType("date");

                    b.Property<Guid?>("NguoiThuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HocPhiId");

                    b.HasIndex("MaGiaoDichNganHang")
                        .IsUnique()
                        .HasFilter("[MaGiaoDichNganHang] IS NOT NULL");

                    b.HasIndex("NguoiThuId");

                    b.ToTable("PhieuThu", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.YeuCauDatLaiMatKhau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HetHanUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDungUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTaoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenBam")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("TokenBam")
                        .IsUnique();

                    b.ToTable("YeuCauDatLaiMatKhau", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GiaoVienQuyen", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("GiaoVienDangNhapNgoai", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("GiaoVienToken", (string)null);
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.BuoiHoc", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassManagement.Api.Entities.HocSinh", "HocSinh")
                        .WithMany("DanhSachBuoiHoc")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.DiemDanh", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.BuoiHoc", "BuoiHoc")
                        .WithOne("DiemDanh")
                        .HasForeignKey("ClassManagement.Api.Entities.DiemDanh", "BuoiHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "NguoiDiemDanh")
                        .WithMany()
                        .HasForeignKey("NguoiDiemDanhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BuoiHoc");

                    b.Navigation("NguoiDiemDanh");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocPhi", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClassManagement.Api.Entities.HocSinh", "HocSinh")
                        .WithMany("DanhSachHocPhi")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocSinh", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "GiaoVien")
                        .WithMany("HocSinhPhuTrach")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.KhungGioHoc", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.HocSinh", "HocSinh")
                        .WithMany("LichHoc")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.NhatKy", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.PhienDangNhap", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "GiaoVien")
                        .WithMany("PhienDangNhap")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.PhieuThu", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.HocPhi", "HocPhi")
                        .WithMany("DanhSachPhieuThu")
                        .HasForeignKey("HocPhiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "NguoiThu")
                        .WithMany()
                        .HasForeignKey("NguoiThuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HocPhi");

                    b.Navigation("NguoiThu");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.YeuCauDatLaiMatKhau", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ClassManagement.Api.Entities.GiaoVien", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.BuoiHoc", b =>
                {
                    b.Navigation("DiemDanh");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.GiaoVien", b =>
                {
                    b.Navigation("HocSinhPhuTrach");

                    b.Navigation("PhienDangNhap");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocPhi", b =>
                {
                    b.Navigation("DanhSachPhieuThu");
                });

            modelBuilder.Entity("ClassManagement.Api.Entities.HocSinh", b =>
                {
                    b.Navigation("DanhSachBuoiHoc");

                    b.Navigation("DanhSachHocPhi");

                    b.Navigation("LichHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
